In [84]:
import pandas as pd
import numpy as np

In [85]:
df = pd.read_csv('H:\winnovation Machine learning\CV Data Life Expectancy Data.csv')
df.head()

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\User\AppData\Local\Temp\ipykernel_6016\2831626042.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df = pd.read_csv('H:\winnovation Machine learning\CV Data Life Expectancy Data.csv')

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   str
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   str
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), str(2)
memory usage: 505.1 KB

In [87]:
df['Country'].nunique()

193

In [88]:
from sklearn.preprocessing import LabelEncoder

In [89]:
le  = LabelEncoder()

In [90]:
df['Country_encoded'] = le.fit_transform(df["Country"])

In [91]:
print(df[['Country', 'Country_encoded']].head(50
))

        Country  Country_encoded
0   Afghanistan                0
1   Afghanistan                0
2   Afghanistan                0
3   Afghanistan                0
4   Afghanistan                0
5   Afghanistan                0
6   Afghanistan                0
7   Afghanistan                0
8   Afghanistan                0
9   Afghanistan                0
10  Afghanistan                0
11  Afghanistan                0
12  Afghanistan                0
13  Afghanistan                0
14  Afghanistan                0
15  Afghanistan                0
16      Albania                1
17      Albania                1
18      Albania                1
19      Albania                1
20      Albania                1
21      Albania                1
22      Albania                1
23      Albania                1
24      Albania                1
25      Albania                1
26      Albania                1
27      Albania                1
28      Albania                1
29      Albania                1
30      Albania                1
31      Albania                1
32      Algeria                2
33      Algeria                2
34      Algeria                2
35      Algeria                2
36      Algeria                2
37      Algeria                2
38      Algeria                2
39      Algeria                2
40      Algeria                2
41      Algeria                2
42      Algeria                2
43      Algeria                2
44      Algeria                2
45      Algeria                2
46      Algeria                2
47      Algeria                2
48       Angola                3
49       Angola                3

In [92]:
df['Status'].value_counts()

Status
Developing    2426
Developed      512
Name: count, dtype: int64

In [93]:
df['developing_status'] = np.where(df['Status'] == 'developing',1,0) 
df['developed_status'] = np.where(df['Status'] == 'developed',1,0)

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   str
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   str
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
 22  Country_encoded                  2938 non-null   int64
 23  developing_status                2938 non-null   int64
 24  developed_status                 2938 non-null   int64
dtypes: float64(16), int64(7), str(2)
memory usage: 574.0 KB

In [95]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
Country_encoded                      0
developing_status                    0
developed_status                     0
dtype: int64

In [96]:
df = df.drop(['Country'], axis=1)

In [97]:
df.shape

(2938, 24)

In [98]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Country_encoded,developing_status,developed_status
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,...,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000,2938.000000,2938.0,2938.0
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,...,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793,95.096324,0.0,0.0
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,...,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920,56.244904,0.0,0.0
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,...,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,0.000000,0.0,0.0
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,...,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000,46.000000,0.0,0.0
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,...,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,93.000000,0.0,0.0
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,...,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000,145.000000,0.0,0.0
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,...,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,192.000000,0.0,0.0

In [99]:
df.isnull().sum()

Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
Country_encoded                      0
developing_status                    0
developed_status                     0
dtype: int64

In [100]:
df.columns

Index(['Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Country_encoded',
       'developing_status', 'developed_status'],
      dtype='str')

In [101]:
  df['Life expectancy '] = df['Life expectancy '].fillna(df['Life expectancy '].median(), inplace=True)
  df['Adult Mortality'] = df['Adult Mortality'].fillna(df['Adult Mortality'].median(), inplace=True)
  df['Hepatitis B'] = df['Hepatitis B'].fillna(df['Hepatitis B'].median(), inplace=True)
  df['Measles '] = df['Measles '].fillna(df['Measles '].median(), inplace=True)
  df[' BMI '] = df[' BMI '].fillna(df[' BMI '].median(), inplace=True)
  df['under-five deaths '] = df['under-five deaths '].fillna(df['under-five deaths '].median(), inplace=True)
  df[' HIV/AIDS'] = df[' HIV/AIDS'].fillna(df[' HIV/AIDS'].median(), inplace=True)
  df['Total expenditure'] = df['Total expenditure'].fillna(df['Total expenditure'].median(), inplace=True)
  df['GDP'] = df['GDP'].fillna(df['GDP'].median(), inplace=True)
  df['Population'] = df['Population'].fillna(df['Population'].median(), inplace=True)
  df[' thinness  1-19 years'] = df[' thinness  1-19 years'].fillna(df[' thinness  1-19 years'].median(), inplace=True)
  df[' thinness 5-9 years'] = df[' thinness 5-9 years'].fillna(df[' thinness 5-9 years'].median(), inplace=True)
  df['Income composition of resources'] = df['Income composition of resources'].fillna(df['Income composition of resources'].median(), inplace=True)
  df['Schooling'] = df['Schooling'].fillna(df['Schooling'].median(), inplace=True)
  df['Alcohol'] = df['Alcohol'].fillna(df['Alcohol'].median(), inplace=True)
  df['Polio'] = df['Polio'].fillna(df['Polio'].median(), inplace=True)
  df['Diphtheria '] = df['Diphtheria '].fillna(df['Diphtheria '].median(), inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Life expectancy '] = df['Life expectancy '].fillna(df['Life expectancy '].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Adult Mortality'] = df['Adult Mortality'].fillna(df['Adult Mortality'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Hepatitis B'] = df['Hepatitis B'].fillna(df['Hepatitis B'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Measles '] = df['Measles '].fillna(df['Measles '].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[' BMI '] = df[' BMI '].fillna(df[' BMI '].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['under-five deaths '] = df['under-five deaths '].fillna(df['under-five deaths '].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[' HIV/AIDS'] = df[' HIV/AIDS'].fillna(df[' HIV/AIDS'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Total expenditure'] = df['Total expenditure'].fillna(df['Total expenditure'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['GDP'] = df['GDP'].fillna(df['GDP'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Population'] = df['Population'].fillna(df['Population'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[' thinness  1-19 years'] = df[' thinness  1-19 years'].fillna(df[' thinness  1-19 years'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[' thinness 5-9 years'] = df[' thinness 5-9 years'].fillna(df[' thinness 5-9 years'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:13: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Income composition of resources'] = df['Income composition of resources'].fillna(df['Income composition of resources'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Schooling'] = df['Schooling'].fillna(df['Schooling'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Alcohol'] = df['Alcohol'].fillna(df['Alcohol'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:16: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Polio'] = df['Polio'].fillna(df['Polio'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_6016\1385911959.py:17: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Diphtheria '] = df['Diphtheria '].fillna(df['Diphtheria '].median(), inplace=True)

In [102]:
df.isnull().sum()

Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
Country_encoded                    0
developing_status                  0
developed_status                   0
dtype: int64

In [103]:
df.columns = df.columns.str.strip()

In [104]:
x = df.drop(['Life expectancy','Status'],axis=1)
y = df['Life expectancy']

In [105]:
import sklearn

In [106]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score ,mean_absolute_error ,mean_absolute_percentage_error

In [107]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [108]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [109]:
model.coef_

array([ 9.82913941e-05, -4.77739337e-02, -3.07554554e-03,  1.72440026e-04,
        7.96292817e-05,  9.39502993e-04, -6.71773226e-05,  2.60934770e-03,
       -5.05139595e-03,  2.28109309e-03,  8.46279552e-05,  2.21999590e-03,
       -1.05976175e-03,  1.52404568e-04,  1.03174458e-08, -4.30804252e-04,
       -4.56686587e-04,  2.69941778e-05,  4.33728794e-04,  1.18599457e-03,
        0.00000000e+00,  0.00000000e+00])

In [110]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [111]:
train_pred[:5]

array([70.94713759, 69.17942422, 70.11204812, 76.78116203, 74.57716591])

In [112]:
y_train.values[:5]

array([72.3, 73. , 74.6, 74.9, 74.8])

In [113]:
test_pred[:5]

array([70.92801317, 73.01291976, 71.53778006, 80.05745914, 53.56814084])

In [114]:
y_train[:5]

456     72.3
462     73.0
2172    74.6
2667    74.9
381     74.8
Name: Life expectancy, dtype: float64

In [115]:
print("Mean Squared Error (MSE):", mean_squared_error(y_test, test_pred))
print("end=Mean Absolute Error (MAE):", mean_absolute_error(y_test, test_pred))
print("mean absolute percentage error:", mean_absolute_percentage_error(y_test, test_pred))

Mean Squared Error (MSE): 38.388547077100455
end=Mean Absolute Error (MAE): 4.251703635803236
mean absolute percentage error: 0.06627570984272943

In [116]:
print("Mean Squared Error (MSE):", mean_squared_error(y_train, train_pred))
print("end=Mean Absolute Error (MAE):", mean_absolute_error(y_train, train_pred))
print("mean absolute percentage error:", mean_absolute_percentage_error(y_train, train_pred)*100)

Mean Squared Error (MSE): 38.2359655691182
end=Mean Absolute Error (MAE): 4.341793270138546
mean absolute percentage error: 6.684447433589027